### ISSUE TITLE
How to migrate my 5 years+ trove of events?

### ISSUE THREAD

**Issue by fleXible** [doksu/TA_sudo#1]
Hi,

I'd just like to leave the question up for discussion, but I already have indexed 5 years+ of Splunk_TA_nix events where sudo events are considered as sourcetype linux_secure or syslog. Any suggestion on how to migrate those now "legacy" events?

Isn't there any better method of getting those sudo events CIMed than changing their sourcetype when indexing as this obviously breaks compatibility with my data ingested up till now.

Best regards,
Felix

**Comment by doksu** [comment]
Hi Felix,

Thanks very much, that's a really good question and I should put this rationale and work-around into the documentation.

The reason I chose to change the sourcetype of sudo events is principally because both the linux_secure and syslog sourcetypes are "overloaded" in the sense they are catch-alls for various log entry types with various formats. This is a problem when trying to normalise sudo events' action (and other fields) to the CIM. A sudo event is considered a failure if a message (vendor_action field) is provided (ie. not null) between the src_user and TTY fields, otherwise it's successful. In this way, it would end up applying the action field with a value of "successful" to _non-sudo_ linux_secure/syslog sourcetyped events, which would both conflict with other TAs and be erroneous.

The second reason a new sourcetype was used is because CIM acceleration is _much_ more efficient when tagging events using indexed field values (ie. the sourcetype) than a string or regular expression. In large distributed environments with substantial syslog sourcetyped events, the impact of this can be significant.

This approach is also advantageous because it prevents duplication of props to apply the same sudo extractions to multiple sourcetypes and puts less search-time field extraction overhead when searching syslog sourcetyped events.

My recommendation would be to start sourcetyping sudo events with the sourcetype "sudo" from now on (the best approach is actually to log sudo events to its own /var/log/sudo file and ingest that with an inputs.conf stanza sourcetype of "sudo") and for backwards compatibility, you could add the following local configs to the TA_sudo app (keeping in mind the normalisation issues above):

eventtypes.conf:
[syslog_sudo_event]
search = index=yourindex sourcetype=linux_secure OR sourcetype=syslog TERM("sudo")

tags.conf:
[eventtype=syslog_sudo_event]
authentication = enabled
privileged = enabled

props.conf:
[linux_secure]
FIELDALIAS-ls_sudo_user = USER AS user
FIELDALIAS-ls_sudo_src = host AS src
FIELDALIAS-ls_sudo_dest = host AS dest
FIELDALIAS-ls_sudo_app = sourcetype AS app
REPORT-ls_sudo_src_user_action = sudo_src_user_action
REPORT-ls_sudo_command = sudo_command
EVAL-action = case(searchmatch("sudo"),if(isnull(vendor_action),"success","failure"))

[syslog]
FIELDALIAS-syslog_sudo_user = USER AS user
FIELDALIAS-syslog_sudo_src = host AS src
FIELDALIAS-syslog_sudo_dest = host AS dest
FIELDALIAS-syslog_sudo_app = sourcetype AS app
REPORT-syslog_sudo_src_user_action = sudo_src_user_action
REPORT-syslog_sudo_command = sudo_command
EVAL-action = case(searchmatch("sudo"),if(isnull(vendor_action),"success","failure"))

N.B. I haven't actually tested this and it assumes the word "sudo" is present in your sudo log events (which isn't always the case). :)

Hope this helps.

Thanks,
Doksu

**Comment by doksu** [comment]
I've tested and updated to fix the config provided above here in the wiki: https://github.com/doksu/TA_sudo/wiki/FAQ and linked to it in the README.

**Comment by fleXible** [comment]
Hi Doksu,

thanks for the quick response and the provided solution. I think now I'll take your app up for a spin on our Dev-environment.

Greetings,
Felix
